
![](https://bids.berkeley.edu/sites/default/files/styles/400x225/public/projects/numpy_project_page.jpg?itok=flrdydei)

---
NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.
    
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.

# Installation of NumPy
If you have Python and PIP already installed on a system, then 
installation of NumPy is very easy.

Install it using this command:
```
    pip install numpy
```

In [1]:
import numpy as np

# Array creation

In [2]:
# creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [3]:
# creating array from tuple
b = np.array((1 , 3, 2))
print("\nArray created using passed tuple:\n", b)


Array created using passed tuple:
 [1 3 2]


In [4]:
# creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print("\nAn array initialized with all zeros:\n", c)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:

# create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print("\nAn array initialized with all 6s. Array type is complex:\n", d)


An array initialized with all 6s. Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [6]:
# create an array with random values
e = np.random.random((2,2))
print("\nA random array:\n", e)


A random array:
 [[0.78869738 0.71825067]
 [0.66755887 0.78922844]]


In [7]:

# create a sequence of integers from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print("\nA sequential array with steps of 5:\n", f)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [8]:
# create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print("\nA sequential array with 10 values between 0 and 5:\n", g)


A sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [9]:
# reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
newarr = arr.reshape(2, 2, 3)
print("\nOriginal array:\n", arr)
print("Reshaped array:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [10]:
# flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
print("\nOriginal array:\n", arr)
print("Fattened array:\n", flarr)


Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


## Arrays in NumPy

In [11]:
# creating array object
arr = np.array([[ 1, 2, 3],
                [ 4, 2, 5]])


In [12]:

# printing type of arr object
print("Array is of type: ", type(arr))

Array is of type:  <class 'numpy.ndarray'>


In [13]:
# printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

No. of dimensions:  2


In [14]:
# printing shape of array
print("Shape of array: ", arr.shape)

Shape of array:  (2, 3)


In [15]:

# printing size (total number of elements) of array
print("Size of array: ", arr.size)

Size of array:  6


In [16]:

# printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array stores elements of type:  int32


## Array Indexing
- **Slicing:**

- **Integer array indexing:** 

- **Boolean array indexing:**

In [17]:

# an exemplar array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

In [18]:
# slicing
temp = arr[:2, ::2]
print("Array with first 2 rows and alternate columns(0 and 2):\n", temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [19]:
# integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print("\nElements at indices (0, 3), (1, 2), (2, 1), (3, 0):\n", temp)


Elements at indices (0, 3), (1, 2), (2, 1), (3, 0):
 [4. 6. 0. 3.]


In [20]:
# boolean array indexing example
cond = arr > 0    # cond is a boolean array
temp = arr[cond]
print("\nElements greater than 0:\n", temp)


Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


## Basic operations
- **Operations on single array:**

In [21]:
a = np.array([1, 2, 5, 3])

In [22]:
# add 1 to every element
print("Adding 1 to every element:", a+1)

Adding 1 to every element: [2 3 6 4]


In [23]:
# subtract 3 from each element
print("Subtracting 3 from each element:", a-3)

Subtracting 3 from each element: [-2 -1  2  0]


In [24]:
# multiply each element by 10
print("Multiplying each element by 10:", a*10)

Multiplying each element by 10: [10 20 50 30]


In [25]:

# square each element
print("Squaring each element:", a**2)

Squaring each element: [ 1  4 25  9]


In [26]:
# modify existing array
a *= 2
print("Doubled each element of original array:", a)

Doubled each element of original array: [ 2  4 10  6]


In [27]:
# transpose of array 
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print("\nOriginal array:\n", a)
print("Transpose of array:\n", a.T)


Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


- ## **Unary operators:**

In [28]:
arr = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]])

In [29]:
# maximum element of array
print("Largest element is:", arr.max())
print("Row-wise maximum elements:", arr.max(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]


In [30]:
# minimum element of array
print("Column-wise minimum elements:", arr.min(axis = 0))

Column-wise minimum elements: [1 1 2]


In [31]:
# sum of array elements
print("Sum of all array elements:", arr.sum())

Sum of all array elements: 38


In [32]:
# cumulative sum along each row
print("Cumulative sum along each row:\n", arr.cumsum(axis = 1))

Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


- # **Binary operators:**

In [33]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[4, 3], 
              [2, 1]])

In [34]:

# add arrays
print("Array sum:\n", a + b)

Array sum:
 [[5 5]
 [5 5]]


In [35]:
# multiply arrays (elementwise multiplication)
print("Array multiplication:\n", a*b)

Array multiplication:
 [[4 6]
 [6 4]]


In [36]:
# matrix multiplication
print("Matrix multiplication:\n", a.dot(b))

Matrix multiplication:
 [[ 8  5]
 [20 13]]


- # **Universal functions (ufunc):**

In [37]:
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print("Sine values of array elements:", np.sin(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [38]:
# exponential values
a = np.array([0, 1, 2, 3])
print("Exponent of array elements:", np.exp(a))

Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]


In [39]:
# square root of array values
print("Square root of array elements:", np.sqrt(a))

Square root of array elements: [0.         1.         1.41421356 1.73205081]


# Sorting array

In [40]:
a = np.array([[1, 4, 2],
              [3, 4,6],
              [0, -1, 5]])

In [41]:
# sorted array
print("Array elements in sorted order:\n", np.sort(a, axis = None))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]


In [42]:
# sort array row-wise
print("Row-wise sorted array:\n", np.sort(a, axis = 1))

Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


In [43]:
# specify sort algorithm
print("Column wise sort by applying merge-sort:\n", np.sort(a, axis = 0, kind = 'mergesort'))

Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [44]:
# example to show sorting of structured array
## set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]
## values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
## creating array
arr = np.array(values, dtype = dtypes)
print("\nArray sorted by names:\n", np.sort(arr, order = 'name'))
print("Array sorted by grauation year and then cgpa:\n", np.sort(arr, order = ['grad_year', 'cgpa']))




Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by grauation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


# Stacking and Splitting

Several arrays can be stacked together along different axes.

- **np.vstack:** To stack arrays along vertical axis.

- **np.hstack:** To stack arrays along horizontal axis.

- **np.column_stack:** To stack 1-D arrays as columns into 2-D arrays.

- **np.concatenate:** To stack arrays along specified axis (axis is passed as argument).

In [45]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

In [46]:
# vertical stacking
print("Vertical stacking:\n", np.vstack((a, b)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [47]:
# horizontal stacking
print("\nHorizontal stacking:\n", np.hstack((a, b)))


Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


In [48]:
c = [5, 6]

# stacking columns
print("\nColumn stacking:\n", np.column_stack((a, c)))


Column stacking:
 [[1 2 5]
 [3 4 6]]


In [49]:

# concatenation method 
print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 1))


Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


For splitting, we have these fuctions:

- **np.hsplit:** Split array along horizontal axis.

- **np.vsplit:** Split array along vertical axis.

- **np.array_split:** Split array along specified axis.

In [50]:
a = np.array([[1, 3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10, 12]])

In [51]:
# horizontal splitting
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2))


Splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]


In [52]:
# vertical splitting
print("\nSplitting along vertical axis into 2 parts:\n", np.vsplit(a, 2))


Splitting along vertical axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


# Some More Numpy Functions - Statistics
- min, max
- mean 
- median
- average
- variance
- standard devidation

In [53]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)


[[1 2 3 4]
 [7 6 2 0]]


In [54]:
print(np.min(a))


0


In [55]:
#Specify axis for the direction in case of multidim array
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[1 2 2 0]
[1 0]


In [56]:
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [57]:
c = np.array([1,5,4,2,0])
print(np.median(c))

# Mean vs Average is Weighted
print(np.mean(c))


# Weights 
w = np.array([1,1,1,1,1])
print(np.average(c,weights=w))

# weighted mean => n1*w1 + n2*w2 / n1+n2 

# Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

#Inbuilt Function
dev= np.std(c)
print(dev)

#Variance
print(myStd**2)
print(np.var(c))

2.0
2.4
2.4
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


# Numpy Random Module

- rand : Random values in a given shape.
- randn : Return a sample (or samples) from the “standard normal” distribution.
- randint : Return random integers from low (inclusive) to high (exclusive).
- random : Return random floats in the half-open interval [0.0, 1.0) 
- choice : Generates a random sample from a given 1-D array
- Shuffle : Shuffles the contents of a sequence

In [58]:
a = np.arange(10) + 5
print(a)

np.random.seed(1)
np.random.shuffle(a)
print(a)

#Returns values from a Standard Normal Distributions
a = np.random.randn(2,3)
print(a)

a = np.random.randint(5,10,3)
print(a)

#Randoly pick one element from a array
element = np.random.choice([1,4,3,2,11,27])
print(element)

[ 5  6  7  8  9 10 11 12 13 14]
[ 7 14 11  9  5  8  6 12 13 10]
[[ 1.5827523  -1.04514683  0.25759352]
 [-1.9593946  -1.50780766 -0.31529207]]
[7 9 6]
4
